# Generated by Django 4.2 on 2024-09-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('rank', models.CharField(choices=[('junior', 'Junior'), ('senior', 'Senior'), ('lead', 'Lead'), ('manager', 'Manager'), ('director', 'Director'), ('executive', 'Executive'), ('intern', 'Intern')], default='junior', help_text='Select the rank or position of the team member.', max_length=20)),
                ('bio', models.TextField()),
                ('profile_image', models.ImageField(help_text='Upload a profile image.', upload_to='team_images/')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('achievements', models.TextField(blank=True, help_text='Mention key achievements or recognitions.', null=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order of appearance in the team listing.')),
                ('date_joined', models.DateField(blank=True, help_text='Date when the team member joined.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Set to False if the member is no longer part of the team.')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['display_order', 'rank', 'name'],
            },
        ),
    ]
