# Generated by Django 4.2 on 2024-09-23 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Rank or position title.', max_length=50, unique=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of the rank, lower numbers appear first.')),
            ],
            options={
                'verbose_name': 'Rank',
                'verbose_name_plural': 'Ranks',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['display_order', 'rank__order', 'name'], 'verbose_name': 'Team Member', 'verbose_name_plural': 'Team Members'},
        ),
        migrations.AlterField(
            model_name='teammember',
            name='rank',
            field=models.ForeignKey(blank=True, help_text='Select the rank or position of the team member.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.rank'),
        ),
    ]
