# Generated by Django 4.2 on 2024-10-02 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
