# Generated by Django 4.2 on 2024-10-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_testimonials_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.CharField(max_length=100)),
                ('projects_completed', models.CharField(max_length=100)),
                ('team_members', models.CharField(max_length=100)),
                ('awards', models.CharField(max_length=100)),
            ],
        ),
    ]
