# Generated by Django 4.2 on 2024-09-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_image1_project_image2_project_image3'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='qoute',
            field=models.TextField(default='default_value', max_length=255),
        ),
    ]
